{
 "title": "Libp2p GossipSub Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(gossipsub_protocol,job)"
    }
   },
   {
    "name": "topic",
    "query": {
     "query": "label_values(gossipsub_topic_subscription_status,topicStr)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GossipSub Protocols",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job, protocol) (gossipsub_protocol)",
     "legendFormat": "{{protocol}} {{job}}"
    }
   ]
  },
  {
   "title": "Peer stream read error coun",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "gossipsub_peer_read_stream_err_count_total",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Gossip sub",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gossipsub msg publish count total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "gossipsub_msg_publish_count_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub msg publish peers total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
     "targets": [
      {
       "expr": "gossipsub_msg_publish_peers_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub direct peers published total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "gossipsub_direct_peers_published_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub fanout peers published total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
     "targets": [
      {
       "expr": "gossipsub_fanout_peers_published_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub floodsub peers published total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "gossipsub_floodsub_peers_published_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossisub duplicate msg delivery delay seconds p50",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(gossisub_duplicate_msg_delivery_delay_seconds{job=~\"$job\" ,topic=~\"$topic\"}[1m])) by (job, le))",
       "legendFormat": "{{job}} p50"
      }
     ]
    },
    {
     "title": "Gossipsub mesh peers published total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "gossipsub_mesh_peers_published_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub msg publish bytes total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "gossipsub_msg_publish_bytes_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub msg forward peers total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "gossipsub_msg_forward_peers_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub msg forward count total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 32 },
     "targets": [
      {
       "expr": "gossipsub_msg_forward_count_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub msg received prevalidation total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "gossipsub_msg_received_prevalidation_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub msg publish seconds",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 32 },
     "targets": [
      {
       "expr": "gossipsub_msg_publish_seconds{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub pre validation invalid total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "gossipsub_pre_validation_invalid_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub msg received error total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 41 },
     "targets": [
      {
       "expr": "gossipsub_msg_received_error_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub pre validation valid total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "gossipsub_pre_validation_valid_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub pre validation duplicate total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 41 },
     "targets": [
      {
       "expr": "gossipsub_pre_validation_duplicate_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub msg received invalid by topic total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "gossipsub_msg_received_invalid_by_topic_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub pre validation unknown status total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 50 },
     "targets": [
      {
       "expr": "gossipsub_pre_validation_unknown_status_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub msg received invalid total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "gossipsub_msg_received_invalid_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossisub duplicate msg late delivery total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 50 },
     "targets": [
      {
       "expr": "gossisub_duplicate_msg_late_delivery_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossisub ignored published duplicate msgs total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "gossisub_ignored_published_duplicate_msgs_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC recv bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "gossipsub_rpc_recv_bytes_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC recv count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 69 },
     "targets": [
      {
       "expr": "gossipsub_rpc_recv_count_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC recv subscription",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 69 },
     "targets": [
      {
       "expr": "gossipsub_rpc_recv_subscription_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC recv message total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 69 },
     "targets": [
      {
       "expr": "gossipsub_rpc_recv_message_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC recv control total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "gossipsub_rpc_recv_control_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC recv ihave total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 78 },
     "targets": [
      {
       "expr": "gossipsub_rpc_recv_ihave_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC recv error count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 78 },
     "targets": [
      {
       "expr": "gossipsub_rpc_recv_err_count_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC recv data error count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 78 },
     "targets": [
      {
       "expr": "gossipsub_rpc_data_err_count_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC recv prune total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 87 },
     "targets": [
      {
       "expr": "gossipsub_rpc_recv_prune_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC recv iwant total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 87 },
     "targets": [
      {
       "expr": "gossipsub_rpc_recv_iwant_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC recv graft total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 87 },
     "targets": [
      {
       "expr": "gossipsub_rpc_recv_graft_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC recv not accepted total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 87 },
     "targets": [
      {
       "expr": "gossipsub_rpc_rcv_not_accepted_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC sent message total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 96 },
     "targets": [
      {
       "expr": "gossipsub_rpc_sent_message_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC sent count total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 96 },
     "targets": [
      {
       "expr": "gossipsub_rpc_sent_count_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC sent iwant total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 96 },
     "targets": [
      {
       "expr": "gossipsub_rpc_sent_iwant_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC sent subscription total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 96 },
     "targets": [
      {
       "expr": "gossipsub_rpc_sent_subscription_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC sent bytes total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "gossipsub_rpc_sent_bytes_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC sent ihave total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 105 },
     "targets": [
      {
       "expr": "gossipsub_rpc_sent_ihave_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC sent graft total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 105 },
     "targets": [
      {
       "expr": "gossipsub_rpc_sent_graft_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC sent prune total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 105 },
     "targets": [
      {
       "expr": "gossipsub_rpc_sent_prune_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC sent control total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 114 },
     "targets": [
      {
       "expr": "gossipsub_rpc_sent_control_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RPC sent idontwant total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 114 },
     "targets": [
      {
       "expr": "gossipsub_rpc_sent_idontwant_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gossipsub score fn calls total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 348 },
     "targets": [
      {
       "expr": "gossipsub_score_fn_calls_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub score fn runs total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 348 },
     "targets": [
      {
       "expr": "gossipsub_score_fn_runs_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub peers by score threshold count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 348 },
     "targets": [
      {
       "expr": "gossipsub_peers_by_score_threshold_count{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub score",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 348 },
     "targets": [
      {
       "expr": "gossipsub_score{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub score per mesh",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 366 },
     "targets": [
      {
       "expr": "gossipsub_score_per_mesh{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub score weights",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 366 },
     "targets": [
      {
       "expr": "gossipsub_score_weights{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub score cache delta p50",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 366 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(gossipsub_score_cache_delta{job=~\"$job\"}[1m])) by (job, le))",
       "legendFormat": "{{job}} p50"
      }
     ]
    },
    {
     "title": "Gossipsub peer stat behaviour penalty p50",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 366 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(gossipsub_peer_stat_behaviour_penalty{job=~\"$job\"}[1m])) by (job, le))",
       "legendFormat": "{{job}} p50"
      }
     ]
    },
    {
     "title": "Gossipsub scoring penalties total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 375 },
     "targets": [
      {
       "expr": "gossipsub_scoring_penalties_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IWantIHave",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gossipsub ihave rcv ignored total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 349 },
     "targets": [
      {
       "expr": "gossipsub_ihave_rcv_ignored_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub ihave rcv msgids total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 349 },
     "targets": [
      {
       "expr": "gossipsub_ihave_rcv_msgids_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub iwant promise delivery seconds p50",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 349 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(gossipsub_iwant_promise_delivery_seconds{job=~\"$job\"}[1m])) by (job, le))",
       "legendFormat": "{{job}} p50"
      }
     ]
    },
    {
     "title": "Gossipsub ihave rcv not seen msgids total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 349 },
     "targets": [
      {
       "expr": "gossipsub_ihave_rcv_not_seen_msgids_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub iwant rcv msgids total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 358 },
     "targets": [
      {
       "expr": "gossipsub_iwant_rcv_msgids_total{job=~\"$job\" ,topic=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub iwant rcv dont have msgids total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 358 },
     "targets": [
      {
       "expr": "gossipsub_iwant_rcv_dont_have_msgids_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub idontwant rcv msgids total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 358 },
     "targets": [
      {
       "expr": "gossipsub_idontwant_rcv_msgids_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub idontwant rcv dont have msgids total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 358 },
     "targets": [
      {
       "expr": "gossipsub_idontwant_rcv_dont_have_msgids_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub iwant promise sent total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 367 },
     "targets": [
      {
       "expr": "gossipsub_iwant_promise_sent_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub iwant promise resolved total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 367 },
     "targets": [
      {
       "expr": "gossipsub_iwant_promise_resolved_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub iwant promise resolved from duplicate total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 367 },
     "targets": [
      {
       "expr": "gossipsub_iwant_promise_resolved_from_duplicate_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub iwant promise resolved peers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 367 },
     "targets": [
      {
       "expr": "gossipsub_iwant_promise_resolved_peers{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub iwant promise broken",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 376 },
     "targets": [
      {
       "expr": "gossipsub_iwant_promise_broken{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub iwant message pruned",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 376 },
     "targets": [
      {
       "expr": "gossipsub_iwant_message_pruned{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossip iwant promise untracked",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 376 },
     "targets": [
      {
       "expr": "gossip_iwant_promise_untracked{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backoff",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gossipsub connected peers backoff seconds p50",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 204 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(gossipsub_connected_peers_backoff_seconds{job=~\"$job\"}[1m])) by (job, le))",
       "legendFormat": "{{job}} p50"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gossipsub cache size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 360 },
     "targets": [
      {
       "expr": "gossipsub_cache_size{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub mcache size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 360 },
     "targets": [
      {
       "expr": "gossipsub_mcache_size{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub mcache not validated count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 360 },
     "targets": [
      {
       "expr": "gossipsub_mcache_not_validated_count{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub fastmsgid cache collision total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 360 },
     "targets": [
      {
       "expr": "gossipsub_fastmsgid_cache_collision_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "New Connection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gossipsub new connection total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 361 },
     "targets": [
      {
       "expr": "gossipsub_new_connection_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "async validation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "accepted messages",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 195 },
     "targets": [
      {
       "expr": "gossipsub_accepted_messages_total{job=~\"$job\", topic=~\"$topic\"}",
       "legendFormat": "{{job}} {{topic}}"
      }
     ]
    },
    {
     "title": "ignored messages",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 195 },
     "targets": [
      {
       "expr": "gossipsub_ignored_messages_total{job=~\"$job\", topic=~\"$topic\"}",
       "legendFormat": "{{job}} {{topic}}"
      }
     ]
    },
    {
     "title": "rejected messages",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 195 },
     "targets": [
      {
       "expr": "gossipsub_rejected_messages_total{job=~\"$job\", topic=~\"$topic\"}",
       "legendFormat": "{{job}} {{topic}}"
      }
     ]
    },
    {
     "title": "unknown validation results",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 195 },
     "targets": [
      {
       "expr": "gossipsub_unknown_validation_results_total{job=~\"$job\", topic=~\"$topic\"}",
       "legendFormat": "{{job}} {{topic}}"
      }
     ]
    },
    {
     "title": "async validation mcache miss",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 204 },
     "targets": [
      {
       "expr": "gossipsub_async_validation_mcache_hit_total{job=~\"$job\", hit=~\"miss\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "async validation unknown first seen count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 204 },
     "targets": [
      {
       "expr": "gossipsub_async_validation_unknown_first_seen_count_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "async validation delay from first seen (p50)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 204 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(gossipsub_async_validation_delay_from_first_seen{job=~\"$job\"}[1m])) by (job, le))",
       "legendFormat": "{{job}} p50"
      }
     ]
    },
    {
     "title": "async validation mcache hit",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 204 },
     "targets": [
      {
       "expr": "gossipsub_async_validation_mcache_hit_total{job=~\"$job\", hit=~\"hit\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "general metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "peer by protocol count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 204 },
     "targets": [
      {
       "expr": "gossipsub_peers_per_protocol_count{job=~\"$job\"}",
       "legendFormat": "{{job}} {{protocol}}"
      }
     ]
    },
    {
     "title": "Gossipsub Heartbeat Duration (p50)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 204 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(gossipsub_heartbeat_duration_seconds_bucket{job=~\"$job\"}[1m])) by (job, le))",
       "legendFormat": "{{job}} p50"
      }
     ]
    },
    {
     "title": "Gossipsub Heartbeat Skipped Dashboard",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 204 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "gossipsub_heartbeat_skipped", "legendFormat": "{{job}}" }
     ]
    }
   ]
  },
  {
   "title": "Mesh",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gossipsub mesh peer count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 213 },
     "targets": [
      {
       "expr": "gossipsub_mesh_peer_count{job=~\"$job\", topicStr=~\"$topic\"}",
       "legendFormat": "{{job}} {{topic}}"
      }
     ]
    },
    {
     "title": "Gossipsub mesh peer inclusion events fanout total",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 213 },
     "targets": [
      {
       "expr": "gossipsub_mesh_peer_inclusion_events_fanout_total{job=~\"$job\", topic=~\"$topic\"}",
       "legendFormat": "{{job}} {{topic}}"
      }
     ]
    },
    {
     "title": "Gossipsub mesh peer inclusion events random total",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 213 },
     "targets": [
      {
       "expr": "gossipsub_mesh_peer_inclusion_events_random_total{job=~\"$job\", topic=~\"$topic\"}",
       "legendFormat": "{{topic}} {{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub mesh peer inclusion events subscribed total",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 225 },
     "targets": [
      {
       "expr": "gossipsub_mesh_peer_inclusion_events_subscribed_total{job=~\"$job\", topic=~\"$topic\"}",
       "legendFormat": "{{topic}} {{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub mesh peer inclusion events outbound total",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 225 },
     "targets": [
      {
       "expr": "gossipsub_mesh_peer_inclusion_events_outbound_total{job=~\"$job\", topic=~\"$topic\"}",
       "legendFormat": "{{topic}} {{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub mesh peer inclusion events not enough total",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 225 },
     "targets": [
      {
       "expr": "gossipsub_mesh_peer_inclusion_events_not_enough_total{job=~\"$job\", topic=~\"$topic\"}",
       "legendFormat": "{{topic}} {{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub mesh peer inclusion events opportunistic total",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 237 },
     "targets": [
      {
       "expr": "gossipsub_mesh_peer_inclusion_events_opportunistic_total{job=~\"$job\", topic=~\"$topic\"}",
       "legendFormat": "{{topic}} {{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub mesh peer inclusion events unknown total",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 237 },
     "targets": [
      {
       "expr": "gossipsub_mesh_peer_inclusion_events_unknown_total{job=~\"$job\", topic=~\"$topic\"}",
       "legendFormat": "{{topic}} {{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub peer churn events disconnected total",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 248 },
     "targets": [
      {
       "expr": "gossipsub_peer_churn_events_disconnected_total{job=~\"$job\", topic=~\"$topic\"}",
       "legendFormat": "{{topic}} {{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub peer churn events bad score total",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 248 },
     "targets": [
      {
       "expr": "gossipsub_peer_churn_events_bad_score_total{job=~\"$job\", topic=~\"$topic\"}",
       "legendFormat": "{{topic}} {{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub peer churn events prune total",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 248 },
     "targets": [
      {
       "expr": "gossipsub_peer_churn_events_prune_total{job=~\"$job\", topic=~\"$topic\"}",
       "legendFormat": "{{topic}} {{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub peer churn events excess total",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 259 },
     "targets": [
      {
       "expr": "gossipsub_peer_churn_events_excess_total{job=~\"$job\", topic=~\"$topic\"}",
       "legendFormat": "{{topic}} {{job}}"
      }
     ]
    },
    {
     "title": "Gossipsub peer churn events unknown total",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 259 },
     "targets": [
      {
       "expr": "gossipsub_mesh_peer_inclusion_events_unknown_total{job=~\"$job\", topic=~\"$topic\"}",
       "legendFormat": "{{topic}} {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Topic - $topic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "topic",
   "collapsed": true,
   "panels": [
    {
     "title": "subscription status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 535 },
     "targets": [
      {
       "expr": "gossipsub_topic_subscription_status{topicStr=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "topic peer count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 535 },
     "targets": [
      {
       "expr": "gossipsub_topic_peer_count{topicStr=~\"$topic\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  }
 ]
}