name: "Feature Request"
description: Suggest a new feature for the project.
title: "[FEATURE] - <title>"
type: "feature"
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: "Problem Description"
      description: Provide a brief explanation of the problem you are solving.
      placeholder: Describe what is the problem you are addressing.
    validations:
      required: true
  - type: textarea
    id: proposed_solution
    attributes:
      label: "Proposed Solution"
      description: Indicate here some basic examples of your feature.
      placeholder: A few specific words about your feature request.
    validations:
      required: true
  - type: textarea
    id: implementation_pr
    attributes:
      label: "Implementation PR"
      description: Pull request used
      placeholder: "#Pull Request ID"
    validations:
      required: false
  - type: textarea
    id: reference_issues
    attributes:
      label: "Reference Issues"
      description: Common issues
      placeholder: "#Issues IDs"
    validations:
      required: false
  - type: textarea
    id: unresolved_question
    attributes:
      label: "Unresolved questions"
      description: What questions still remain unresolved ?
      placeholder: Identify any unresolved issues.
    validations:
      required: false
  - type: textarea
    id: additional_info
    attributes:
      label: "Additional Information"
      description: Any additional information or any drawbacks ?
      placeholder: Identify any unresolved issues.
    validations:
      required: false
