name: Benchmark
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  pages: write
  id-token: write
  contents: write

jobs:
  benchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - shell: bash
        run: |
          pnpm install --no-frozen-lockfile

      - shell: bash
        run: |
          cd packages/object
          pnpm run benchmark

      - shell: bash
        run: |
          cd packages/node
          pnpm run benchmark

      - name: Restore cached benchmark data
        id: restore-benchmark-data
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-benchmark-${{ github.run_id }}
          path: ./cache
          restore-keys: |
            ${{ runner.os }}-benchmark-

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmark.js Benchmark
          tool: "benchmarkjs"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file-path: packages/benchmark-output.txt
          alert-threshold: "130%"
          fail-on-alert: ${{ github.event_name != 'push' }}
          comment-on-alert: ${{ github.event_name == 'push' }}
          summary-always: true
          gh-pages-branch: main
          skip-fetch-gh-pages: ${{ github.event_name == 'push' }}
          benchmark-data-dir-path: ./cache/benchmarks

      - name: Store benchmark data
        uses: actions/cache/save@v4
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          key: ${{ steps.restore-benchmark-data.outputs.cache-primary-key }}
          path: ./cache

  docs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Release docs
    permissions:
      pages: write
      id-token: write
    needs:
      - benchmark
    uses: ./.github/workflows/docs.yml
