name: Benchmark
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: benchmark
      - name: Build
        run: |
          pnpm install
          cd packages/node
          pnpm build
      - name: Benchmark result
        id: benchmark-result
        run: |
          if [ -f ./cache/benchmark-main.json ]; then
            pnpm run bench --run --outputJson benchmark.json --compare ./cache/benchmark-main.json > benchmark.txt
          else
            pnpm run bench --run --outputJson benchmark.json > benchmark.txt
          fi
          cat benchmark.txt >> $GITHUB_STEP_SUMMARY
      - run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: branch
      - name: Store benchmark dataq
        if: steps.branch.outputs.branch == 'main'
        run: cp benchmark.json ./cache/benchmark-main.json
