name: Build Packages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  # node builds all packages
  build-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - shell: bash
        run: |
          cd packages/node
          pnpm install
          pnpm build

  build-example-canvas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - shell: bash
        run: |
          pnpm install
          cd packages/node
          pnpm build
          cd ../../examples/canvas
          pnpm build

  build-example-chat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - shell: bash
        run: |
          pnpm install
          cd packages/node
          pnpm build
          cd ../../examples/chat
          pnpm build
