name: Build Packages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - shell: bash
        run: |
          pnpm install --no-frozen-lockfile

  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: List examples
        id: list-examples
        run: |
          echo "examples=$(ls -d examples/*/ | xargs -n 1 basename | jq -R -s -c 'split("\n")[:-1]'))" >> $GITHUB_OUTPUT
      - name: Set Matrix
        id: set-matrix
        run: |
          echo "matrix={\"example\": ${{ steps.list-examples.outputs.examples }}}" >> $GITHUB_OUTPUT

  build-examples:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - shell: bash
        run: |
          pnpm install --no-frozen-lockfile
          cd examples/${{ matrix.example }}
          pnpm build
