name: Code quality
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    name: Run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.10.0
      - shell: bash
        run: |
          pnpm install --no-frozen-lockfile

      - shell: bash
        run: |
          cd packages/object
          pnpm run lint
