name: Code quality
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ESLint
        uses: sibiraj-s/action-eslint@v3
        with:
          version: latest
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
