name: Generate Flame Graph

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generate-flamegraph:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install -y perl

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - shell: bash
        run: |
          pnpm install --no-frozen-lockfile
          cd packages/object
          pnpm run flamegraph

      - name: Clone FlameGraph repository
        run: git clone https://github.com/brendangregg/FlameGraph.git

      - name: Generate Flame Graph
        run: perf script > out.perf && ~/FlameGraph/stackcollapse-perf.pl out.perf > out.folded && ~/FlameGraph/flamegraph.pl out.folded > flamegraph.svg
