name: Workflow - release
on:
  release:
    types: [published]
jobs:
  npm_publish:
    name: Publish packages to npmjs
    uses: ./.github/workflows/npm-publish.yml
  
  build_docker_images:
    name: Build Docker Images
    needs:
      - npm_publish
    uses: ./.github/workflows/docker.yml